name: env_submission
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2024.2.2
  - intel-openmp=2024.1.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libhwloc=2.10.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libsqlite=3.45.3
  - libxml2=2.12.6
  - libzlib=1.3.1
  - mkl=2024.1.0
  - numpy=1.21.6
  - openssl=3.2.1
  - pandas=1.2.3
  - pip=24.0=pyhd8ed1ab_0
  - pthreads-win32==2.9.1
  - python=3.7.12
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.7=4_cp37m
  - pytz=2024.1=pyhd8ed1ab_0
  - setuptools=59.8.0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3
  - tbb=2021.12.0
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.34.2=py37_0
  - pip:
    - absl-py==2.1.0
    - astor==0.8.1
    - gast==0.5.4
    - grpcio==1.62.1
    - h5py==3.8.0
    - importlib-metadata==6.7.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.4.4
    - markupsafe==2.1.5
    - mock==5.1.0
    - protobuf==4.24.4
    - tensorboard==1.13.1
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - termcolor==2.3.0
    - typing-extensions==4.7.1
    - werkzeug==2.2.3
    - zipp==3.15.0

